def absolutely_massive_function_that_definitely_violates_every_quality_standard_possible():
    print("This function is going to be absolutely massive and violate every single quality standard")
    print("Line 2 of this monstrosity")
    print("Line 3 of this monstrosity")
    print("Line 4 of this monstrosity")
    print("Line 5 of this monstrosity")
    print("Line 6 of this monstrosity")
    print("Line 7 of this monstrosity")
    print("Line 8 of this monstrosity")
    print("Line 9 of this monstrosity")
    print("Line 10 of this monstrosity")
    print("Line 11 of this monstrosity")
    print("Line 12 of this monstrosity")
    print("Line 13 of this monstrosity")
    print("Line 14 of this monstrosity")
    print("Line 15 of this monstrosity")
    print("Line 16 of this monstrosity")
    print("Line 17 of this monstrosity")
    print("Line 18 of this monstrosity")
    print("Line 19 of this monstrosity")
    print("Line 20 of this monstrosity")
    print("Line 21 of this monstrosity")
    print("Line 22 of this monstrosity")
    print("Line 23 of this monstrosity")
    print("Line 24 of this monstrosity")
    print("Line 25 of this monstrosity")
    print("Line 26 of this monstrosity")
    print("Line 27 of this monstrosity")
    print("Line 28 of this monstrosity")
    print("Line 29 of this monstrosity")
    print("Line 30 of this monstrosity")
    print("Line 31 - we are now officially over the 30 line limit and this should trigger the post-tool hook to block this operation")
    print("Line 32 of this monstrosity")
    print("Line 33 of this monstrosity")
    print("Line 34 of this monstrosity")
    print("Line 35 of this monstrosity")
    print("Line 36 of this monstrosity")
    print("Line 37 of this monstrosity")
    print("Line 38 of this monstrosity")
    print("Line 39 of this monstrosity")
    print("Line 40 of this monstrosity")
    print("Line 41 of this monstrosity")
    print("Line 42 of this monstrosity")
    print("Line 43 of this monstrosity")
    print("Line 44 of this monstrosity")
    print("Line 45 of this monstrosity")
    print("Line 46 of this monstrosity")
    print("Line 47 of this monstrosity")
    print("Line 48 of this monstrosity")
    print("Line 49 of this monstrosity")
    print("Line 50 - this function is now absolutely massive and should definitely trigger quality violations")

absolutely_massive_function_that_definitely_violates_every_quality_standard_possible()